apiVersion: v1
kind: ConfigMap
metadata:
  name: zbxtg-config
  labels:
    app: zbxtg
data:
  poll-interval: "60"
  log-level: "INFO"
  min-severity: "2"
  max-retries: "3"
  retry-delay: "5"
  edit-on-update: "true"
  mark-resolved: "true"
  delete-resolved-after: "3600"
  zabbix-ssl-verify: "true"
